version: '2'

services:
  elasticsearch:
    container_name: nuforc-elasticsearch
    image: nuforc-elasticsearch/latest
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    build:
      context: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"