version: '2'

services:
  elasticsearch:
    container_name: nuforc-elasticsearch
    image: elasticsearch:5.6.10
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    build:
      context: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - back

  web:
    container_name: nuforc-nginx
    image: nuforc-web-nginx
    volumes:
      - ./web/nuforc-web/staging:/usr/share/nginx/html
    build:
      context: ./web
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - front
      - back

networks:
  front:
    # Use a custom driver
    driver: bridge
  back:
    # Use a custom driver
    driver: bridge