version: '2'

services:
  elasticsearch:
    container_name: mock-elasticsearch
    image: jamesdbloom/mockserver
    ports:
      - "9200:9200"
    networks:
      - back
    command: /opt/mockserver/run_mockserver.sh -logLevel INFO -serverPort 9200

  web:
    container_name: nuforc-nginx
    image: jameskbride/nuforc-web-nginx
    volumes:
      - ./web/nuforc-web/staging:/usr/share/nginx/html
    build:
      context: ./web
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - front
      - back

networks:
  front:
    # Use a custom driver
    driver: bridge
  back:
    # Use a custom driver
    driver: bridge