version: '2'

services:

  elasticsearch:
    container_name: nuforc-elasticsearch
    image: jameskbride/elasticsearch
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    build:
      context: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  web:
    container_name: nuforc-nginx
    image: jameskbride/nuforc-web-nginx
    build:
      context: ./web
    ports:
      - "80:80"
      - "8080:8080"
    links:
      - elasticsearch